### PR TITLE
Draft: Biology and Software

### PR DESCRIPTION
**Pull request by as-cii**
@exalted: could you have a look, please? :grin:

### CODE REVIEW

**Comment by exalted** [comment]
@as-cii I will take a look tonight :+1:

**Comment by as-cii** [comment]
Thank you @exalted :)

**Comment by exalted** [comment]
:bow:

**Comment by exalted** [comment]
http://as-cii.com/2015/02/biology-and-software.html :cool:

**Comment by exalted** [comment]
Ha-ha! Fu**ing emojis missing?

**Comment by as-cii** [comment]
Some Jekyll issue, having a look right now :/


—
Antonio Scandurra

**Comment by as-cii** [comment]
@exalted Check it out :wink:

**Comment by exalted** [comment]
Much better! :+1:

**Pull request merged**
